#ifndef __org_openoffice_ezodfmenu_ezodfmenu_idl__
#define __org_openoffice_ezodfmenu_ezodfmenu_idl__

#include <org/openoffice/ezodfmenu/XeZODFMenu.idl>
module org { module openoffice { module ezodfmenu { 	

	service eZODFMenu : org::openoffice::ezodfmenu::XeZODFMenu {

	};

 }; }; };
#endif
